# Actuator default configuration for Ecommerce microservices
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,env
management.endpoint.env.show-values=always
