# Actuator settings (Conditional via enableActuator)
management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always
management.endpoint.env.show-values=always
